log =    /misc/disk15/scratch/brian/trash/restore_$(infile)_$(excludeATWD).log
output = /misc/disk15/scratch/brian/trash/restore_$(infile)_$(excludeATWD)..out
error =  /misc/disk15/scratch/brian/trash/restore_$(infile)_$(excludeATWD)..err


request_cpus = 1
request_memory = 4000MB
request_disk = 3GB
Universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = job.sh
arguments = $(indir) $(infile) $(outdir) $(outfile) $(excludeATWD)

queue