variables:
  charge:
    variable: "Homogenized_QTot"
    value: "value"
  ndoms:
    variable: "HitMultiplicityValues_unified"
    value: "n_hit_doms"
  speed:
    variable: "LineFit_unified"
    value: "speed"
  zenith:
    variable: "LineFit_unified"
    value: "zenith"

juliet:
  nue:
    high_energy:
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/nue/high_energy/l2_prime/nue_high_energy_l2_prime_1k_merged.hd5"
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/nue/high_energy/l2_prime/1/Level2_prime_00000001.hd5"
      # file_cteq5: "/disk20/users/brian/IceCube/unified_naming/original/nue_high_energy_l2_prime_1k_merged.hd5"
      file_cteq5: "/disk20/users/brian/IceCube/juliet/nue_high_energy_merged_1k.hdf5"
      file_csms: "/disk20/users/brian/IceCube/unified_naming/original/nue_high_energy_l2_prime_1k_merged_csms.hd5"
      n_files: 1000
  numu:
    high_energy:
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/numu/high_energy/l2_prime/numu_high_energy_l2_prime_1k_merged.hd5"
      # file_cteq5: "/disk20/users/brian/IceCube/unified_naming/original/numu_high_energy_l2_prime_1k_merged.hd5"
      file_cteq5: "/disk20/users/brian/IceCube/juliet/numu_high_energy_merged_1k.hdf5"
      file_csms: "/disk20/users/brian/IceCube/unified_naming/original/numu_high_energy_l2_prime_1k_merged.hd5"
      n_files: 1000
  nutau:
    high_energy:
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/nutau/high_energy/l2_prime/nutau_high_energy_l2_prime_1k_merged.hd5"
      # file_cteq5: "/disk20/users/brian/IceCube/unified_naming/original/nutau_high_energy_l2_prime_1k_merged.hd5"
      file_cteq5: "/disk20/users/brian/IceCube/juliet/nutau_high_energy_merged_1k.hdf5"
      file_csms: "/disk20/users/brian/IceCube/unified_naming/original/numu_high_energy_l2_prime_1k_merged.hd5"
      n_files: 1000
  mu:
    high_energy:
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/mu/high_energy/l2_prime/mu_high_energy_l2_prime_1k_merged.hd5"
      # file_cteq5: "/disk20/users/brian/IceCube/unified_naming/original/mu_high_energy_l2_prime_1k_merged.hd5"
      file_cteq5: "/disk20/users/brian/IceCube/juliet/mu_high_energy_merged_1k.hdf5"
      file_csms: "/disk20/users/brian/IceCube/unified_naming/original/numu_high_energy_l2_prime_1k_merged.hd5"
      n_files: 1000
  tau:
    high_energy:
      # file: "/home/mmeier/data/simulations/table_based_sim/juliet/tau/high_energy/l2_prime/tau_high_energy_l2_prime_1k_merged.hd5"
      # file_cteq5: "/disk20/users/brian/IceCube/unified_naming/original/numu_high_energy_l2_prime_1k_merged.hd5"
      file_cteq5: "/disk20/users/brian/IceCube/juliet/tau_high_energy_merged_1k.hdf5"
      file_csms: "/disk20/users/brian/IceCube/unified_naming/original/tau_high_energy_l2_prime_1k_merged.hd5"
      n_files: 1000


burn_sample:
  IC86-I-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-I-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-I-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/unified_naming/original/combo_IC86-I-pass2_L4.hdf5"
    livetime: 2721082.25
  IC86-II-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2_smaller.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/unified_naming/original/combo_IC86-II-pass2_L4.hdf5"
    livetime: 2804133.57
  IC86-III-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-III-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-III-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/unified_naming/original/combo_IC86-III-pass2_L4.hdf5"
    livetime: 2948421.03



nugen:
  nue:
    file: "/disk20/users/brian/IceCube/sim/nugen/combo_21218.hdf5"
    # file: "/disk20/users/brian/IceCube/unified_naming/original/combo_21218.hdf5"
    n_files: 1000
    # file: "/disk20/users/brian/IceCube/unified_naming/original/combo_v2_21218.hdf5"
    # n_files: 11991
  numu:
    file: "/disk20/users/brian/IceCube/sim/nugen/combo_21220.hdf5"
    # file: "/disk20/users/brian/IceCube/unified_naming/original/combo_21220.hdf5"
    n_files: 1000


corsika:
  "20787":
    # file: "/disk20/users/brian/IceCube/sim/CORSIKA-in-ice/combo_20787.hdf5"
    file: "/disk20/users/brian/IceCube/unified_naming/original/combo_20787.hdf5"
    n_files: 10000
    # file: "/disk20/users/brian/IceCube/sim/CORSIKA-in-ice/combo_20787_smaller.hdf5"
    # n_files: 1000
