variables:
  charge:
    variable: "Homogenized_QTot"
    value: "value"
  ndoms:
    variable: "CVMultiplicity"
    value: "n_hit_doms"
  speed:
    variable: "LineFit"
    value: "speed"
  zenith:
    variable: "LineFit"
    value: "zenith"

juliet:
  nue:
    high_energy:
      file: "/disk20/users/brian/IceCube/juliet/nue_high_energy_merged_998files.hdf5"
      n_files: 998
    very_high_energy:
      file: "/disk20/users/brian/IceCube/juliet/nue_very_high_energy_merged_999files.hdf5"
      n_files: 999 
  numu:
    high_energy:
      file: "/disk20/users/brian/IceCube/juliet/numu_high_energy_merged_999files.hdf5"
      n_files: 999
    very_high_energy:
      file: "/disk20/users/brian/IceCube/juliet/numu_very_high_energy_merged_999files.hdf5"
      n_files: 999
  nutau:
    high_energy:
      file: "/disk20/users/brian/IceCube/juliet/nutau_high_energy_merged_996files.hdf5"
      n_files: 996
    very_high_energy:
      file: "/disk20/users/brian/IceCube/juliet/nutau_very_high_energy_merged_999files.hdf5"
      n_files: 999
  mu:
    high_energy:
      file: "/disk20/users/brian/IceCube/juliet/mu_high_energy_merged_998files.hdf5"
      n_files: 998
    very_high_energy:
      file: "/disk20/users/brian/IceCube/juliet/mu_very_high_energy_merged_999files.hdf5"
      n_files: 999
  tau:
    high_energy:
      file: "/disk20/users/brian/IceCube/juliet/tau_high_energy_merged_999files.hdf5"
      n_files: 999
    very_high_energy:
      file: "/disk20/users/brian/IceCube/juliet/tau_very_high_energy_merged_999files.hdf5"
      n_files: 999


# juliet:
#   nue:
#     high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/nue_high_energy_merged_9996files.hdf5 "
#       n_files: 9996
#     very_high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/nue_very_high_energy_merged_2000files.hdf5"
#       n_files: 2000 
#   numu:
#     high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/numu_high_energy_merged_9998files.hdf5 "
#       n_files: 9998
#     very_high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/numu_very_high_energy_merged_2000files.hdf5"
#       n_files: 2000
#   nutau:
#     high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/nutau_high_energy_merged_9977files.hdf5"
#       n_files: 9977
#     very_high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/nutau_very_high_energy_merged_1997files.hdf5"
#       n_files: 1997
#   mu:
#     high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/mu_high_energy_merged_9999files.hdf5"
#       n_files: 9999
#     very_high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/mu_very_high_energy_merged_4460files.hdf5"
#       n_files: 4460
#   tau:
#     high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/tau_high_energy_merged_10000files.hdf5"
#       n_files: 10000
#     very_high_energy:
#       file: "/disk20/users/brian/IceCube/juliet/l2_prime/tau_very_high_energy_merged_2000files.hdf5"
#       n_files: 2000


burn_sample:
  IC86-I-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-I-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-I-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/data/combo_IC86-I-pass2_L4.hdf5"
    livetime: 2721082.25
  IC86-II-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2_smaller.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/data/combo_IC86-II-pass2_L4.hdf5"
    livetime: 2804133.57
  IC86-III-pass2:
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-III-pass2.hdf5"
    # file: "/disk20/users/brian/IceCube/data/combo_IC86-III-pass2_L4.hdf5"
    file: "/disk20/users/brian/IceCube/data/combo_IC86-III-pass2_L4.hdf5"
    livetime: 2948421.03

nugen:
  nue:
    file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21218_11991files.hdf5"
    n_files: 11991
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21218_2756files.hdf5"
    # n_files: 2756 
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21218_998files.hdf5"
    # n_files: 998
  numu:
    file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21220_10000files.hdf5"
    n_files: 10000
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21220_3000files.hdf5"
    # n_files: 3000
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21220_1000files.hdf5"
    # n_files: 1000
  nutau:
    file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21221_10000files.hdf5"
    n_files: 10000
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21221_3000files.hdf5"
    # n_files: 3000
    # file: "/disk20/users/brian/IceCube/nugen/hdf5/merged_21221_1000files.hdf5"
    # n_files: 1000


corsika:
  "20787":
    file: "/disk20/users/brian/IceCube/corsika/combo_20787.hdf5"
    n_files: 10000
    # file: "/disk20/users/brian/IceCube/corsika/combo_20787_smaller.hdf5"
    # n_files: 1000
  "21962_fe":
    file: "/disk20/users/brian/IceCube/corsika/level4/hdf5/corsika_21962_merged_fe_9969files.hdf5"
    n_files: 9969
  "21962_p":
    file: "/disk20/users/brian/IceCube/corsika/level4/hdf5/corsika_21962_merged_p_9969files.hdf5"
    n_files: 9969
  "22023_fe":
    file: "/disk20/users/brian/IceCube/corsika/level4/hdf5/corsika_22023_merged_fe_9991files.hdf5"
    n_files: 9991
  "22023_p":
    file: "/disk20/users/brian/IceCube/corsika/level4/hdf5/corsika_22023_merged_p_9991files.hdf5"
    n_files: 9991

