log    = /scratch/brianclark/Gen2/log/convert.$(Process).log
output = /scratch/brianclark/Gen2/out/convert.$(Process).out
error  = /scratch/brianclark/Gen2/err/convert.$(Process).err

request_cpus = 1
request_memory = 1GB
request_disk = 1GB
Universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
+TransferOutput = ""

executable = job.sh
arguments = $(inputfile) $(outputfile) 

queue