log    = /scratch/brian/trash/log/$(infile).log
output = /scratch/brian/trash/out/$(infile).out
error = /scratch/brian/trash/err/$(infile).err

request_cpus = 1
request_memory = 4GB
request_disk = 2GB
Universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Requirements = !regexp("campari", Machine) && !regexp("olive", Machine)

executable = job.sh
arguments = $(indir) $(infile) $(outdir) $(outfile)

queue