name: ehe
channels:
  - conda-forge
dependencies:
  - python >=3.8
  - numpy
  - scipy
  - h5py
  - wquantiles
  - matplotlib
  - ipykernel
  - pandas
  - pyyaml
  - pip
  - notebook
  - pip:
    - tables
    - nb-clean
    - git+https://github.com/clark2668/ehefluxes.git
