log    = /scratch/brian/trash/log/$(infile).log
output = /scratch/brian/trash/out/$(infile).out
error = /scratch/brian/trash/err/$(infile).err

request_cpus = 1
request_memory = 1GB
request_disk = 1GB
Universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = job.sh
#arguments = $(indir) $(infile) $(outdir) $(outfile) $(corsel)
arguments = $(indir) $(infile) $(outdir) $(outfile) $(corsel)

queue